apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-svc
  name: person-svc
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    nodePort: 30001
  selector:
    service: person-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-svc
  name: person-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-svc
  template:
    metadata:
      labels:
        service: person-svc
    spec:
      containers:
      - image: tomiwasalau01/person-svc:latest
        name: person-svc
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
